#+Author: Alex Rosegrid
#+Title: CHIP-8 Emulator - Specs Sheet and Guide
#+Startup: indent

This 'guide' largely serves as a knowledge bank of sorts for the *eventual* rewrite of the emulator; one that it is due for, particularly in the architecture of the code base.

* The CHIP-8
For what it's worth, the CHIP-8 was never an actual hardware device, and instead an interpreter written for old PCs with scarcely a few KiBs of memory.


* Specs

** Memory
Its meant to have a byte addressable space of upto 4KiB, evidently the upper limit for the machines of the time.
The first 512B /(=0x000 (0)= to =0x1FF (512)=)/ are to be treated as inaccessible (except, perhaps, a standard hexadecimal font pack), since that's where the original interpreter was expected to lie and a valid CHIP-8 ROM would not try to access the region.
Note that this is an emulator for a machine that ran the CHIP-8 interpreter and uses modern graphs that merely mimics the graphic capabilities of the computers of the time and can not fit inside that memory limit; it does not *need* to, since CHIP-8 interpreter need not be loaded in for our purposes.
We are, thus, left with an effective address space from =0x200 (512)= to =0xFFF (4095)=.
As per the original specification, a 32B (16 ✕ 2B) stack exists independently of the main memory (remembers, the CHIP-8 was never a physical machine).
*** Registers
16 general purpose (call them =V/x/=) 8-bit registers are required. =VF= (The 16th register) is used as a *Flag Register* by some instructions (Which doesn't seem to fit my idea of a /general/ purpose register, but most literature I found count it as such).
Additionally,
  - One 16-bit *Index Register* (=I=) for storing memory addresses.
  - Two 8-bit *Timer Registers* (=D= and =S=) for delay and sound timers, respectively.
  - One 8-bit *Stack Pointer* (=SP=)
  - One 16-bit *Program Counter* (=PC=)
Practically, =I= and =PC= only ever require the first 12 bits of their designated capacities.

** Keyboard (Input)
Computers of the time used a *16 key hexadecimal key* grid for input.
As such, we require a mapping of the form:
|   1 | 2 |   3 | 0xC |
|   4 | 5 |   6 | 0xD |
|   7 | 8 |   9 | 0xE |
| 0xA | 0 | 0xB | 0xF |
The current implementation maps this into the /QWERTY/ layout as:
| 1 | 2 | 3 | 4 |
| Q | W | E | R |
| A | S | D | F |
| Z | X | C | V |

** Display (Output)
Essentially, a *64✕32 grid*; black and white, as per the original specifications.
*** Sprites and Fonts
Graphics are drawn using a *sprite* specification. A sprite itself is a grid no larger than *8✕15* (at most 8 blocks wide, and at most 15 blocks deep).
As mentioned in [[*Memory][Memory]], a font pack may be loaded. A font is a special sprite, with the dimensions *4✕5* (4 blocks wide, 5 blocks deep).
For convenience of representation and storage, the fonts are formally 8 blocks wide, where only the first 4 are ever turned on.

** Clock / Timers
The CPU for the original seems to have been /something/ *under 1MHz*. The current implementation sets it to *540Hz* but it may be via JSON/CLI.
*** Delay Timer
An 8-bit *60Hz* counter used for timing, that decremented each second if set to a non zero value programmatically.
*** Sound Timer
A similar 8-bit counter used to specify speaker/buzzer duration, that decremented as above. This buzzer is the only audio output provided by the machine.
/The current implementation does not handle audio at all./

** The Instruction Set
Generally speaking, the instructions may be decoded as:
  - The 1st nibble determine the overall 'group' the instruction refers to.
  - The 2nd and 3rd nibbles (=X= and =Y=), if they exist, specify which registers are being operated on.
  - =N=, =NN=, and =NNN= direcly specify 4, 8, and 12 bit numbers respectively.
1. Group =0=: Exec machine instruction. Only 2 shall be implemented
    * =00E0=: Clear screen
    * =00EE=: Return from function call
2. =1NNN=: Jump to NNN
3. =2NNN=: Jump to NNN as function call
4. =3XNN=: Skip the next instruction if VX == NN
5. =4XNN=: Complement of 3XNN
6. =5XY0=: Skip if VX == VY
7. =6XNN=: Set VX = NN
8. =7XNN=: Set VX = VX + NN
9. Group =8XY=: Arithmetic and Logical
    * =0=: Set VX = VY
    * =1=: Set VX = VX | VY
    * =2=: Set VX = VX & VY
    * =3=: Set VX = VX ^ VY (XOR)
    * =4=: Set VX = VX + VY
    * =5=: Set VX = VX - VY
    * =6=: Set VX = VY >> 1, may ignore VY and bitshift VX
    * =7=: Set VX = VY - VX
    * =E=: Set VX = VY << 1, may ignore VY and bitshift VX
10. =9XY0=: Complement of =5XY0=
11. =ANNN=: Set I = NNN
12. =BNNN=: Jump to (V0 + NNN)
    * or, =BXNN=: Jump to (VX + NN)
13. =CXNN=: Set VX = (RANDOM NUMBER) & NN
14. =DXYN=: Draw at (VX, VY) an N pixels tall image found at address I
15. Group =E=: Key press
    * =EX9E=: Skip next instruction if key VX is pressed
    * =EXA1=: Complement of EX9E
16. Group =F=:
    * =FX07=: Set VX = DT
    * =FX15=: Set DT = VX
    * =FX18=: Set ST = VX
    * =FX1E=: Set I = I + VX, set VF = 1 if I exceeds 0x1000
    * =FX0A=: Blocking Input, set VX = Input
    * =FX29=: Point I to the address of the font for the character in VX
    * =FX33=: Copy the decimal representation of VX to address I... (String)
    * =FX55=: Copy V0...VX to address I...(I+X)
    * =FX65=: Copy address I...(I+X) to V0...VX


* References
- [[http://devernay.free.fr/hacks/chip8/C8TECH10.HTM][cowgod]] provides an extensive technical reference. This was /not/ what I referenced the first time I wrote the emulator.
- [[https://tobiasvl.github.io/blog/write-a-chip-8-emulator/][tobiasvl]] provides a more detailed explanation on supported OPCODES.
